Sprint 3
Bezumstvo/middle.messenger.praktikum.yandex pull request #15
Opened 2022-08-31 13:45 UTC by Bezumstvo

добавлено:
Router, WebSocket, API
тестирование Mocha, Chai
безопасность helmet и express-rate-limit

2022-08-31 16:47 UTC, agadoev requested changes
Привет
Основные моменты, над которыми стоит поработать
1) Структура проекта - сейчас почти весь код находится в папке modules. Ты можешь создать разные папки - core, utils, helpres, api, controllers, services, что захочешь. Чем сильнее ты дробишь свой проект, тем легче с ним будет потом работать
2) Сейчас очень много логики в app.ts. Ее точно нужно распутывать и помещать в компоненты/сервисы. Когда все в одном файле/функции, код получается слишком связанным и мы оказываемся в такой ситуации, что чтобы изменить какую-то одну вещь, нужно помнить, что мы можем что-то где-то сломать. Эта лишняя когнитивная нагрузка, которая делает работу над проектом сложнее

Посоветую 3 источника, которые смогут помочь (мне помогли)
1) Книга "Чистый код" Роберта Мартина
2) Книга "Чистая архитектура" Роберта Мартина
3) Доклад "Simple Made Easy" Ричи Хикки 

Пока что код не могу принять, давай попробуем его улучшить и посмотрим, как двигаться дальше

2022-08-31 16:47 UTC, agadoev commented on package.json
> +    "buildAll": "parcel build ./src/index.html --no-source-maps && parcel build ./src/modules/Fetch.ts --no-source-maps --no-scope-hoist --no-optimize --no-content-hash",
Думаю, что тут стоит добавить скрипт для запуска eslint'a и stylelint'a. А то зависимости есть, но не используются

2022-08-31 16:47 UTC, agadoev commented on src/modules/form.css
>  }
в одной папке не должны находиться и .ts и .css файлы. Как вариант, можешь создать папку assets или public и хранить там стили

2022-08-31 16:47 UTC, agadoev commented on src/modules/route.spec.ts
> +import { Block } from "./Block";
Есть отдельная папка tests, но почему-то тесты лежат в исходниках. Логичнее было бы поместить их как раз в папку tests

2022-08-31 16:47 UTC, agadoev commented on src/modules/Validate.ts
>      }
Валидатор не должен возвращать строку, он должен возвращать только boolean. Существует принцип единственной ответственности (SRP), который гласит, что метод (класс, функция, модуль и тд) должен иметь одну и только одну причину для изменения. Сейчас я могу изменить этот метод по двум причинам: 
1) Если хочу изменить текст ошибки
2) Если хочу изменить правило валидации

То, что отображается на экране никак не должно быть связано с валидацией и должно находидиться на уровне отображения, т.е. в компоненте, который рендерит шаблон

2022-08-31 16:47 UTC, agadoev commented on src/modules/Fetch.ts
>  		POST: 'POST',
```suggestion
    Method: TMethod
```

2022-08-31 16:47 UTC, agadoev commented on src/modules/Fetch.ts
> +    DELETE: Methods
Я думаю, что можно спокойно обойтись без MethodsCollection. Использование union type на первой строке - отличный вариант. Сейчас MethodsCollection выглядит лишним кодом.

2022-08-31 16:47 UTC, agadoev commented on src/modules/Fetch.ts
> +            const isGet = (method === ctxFetch.METHODS.GET);
```suggestion
            const isGet = (method === 'GET');
```

2022-08-31 16:47 UTC, agadoev commented on src/modules/Fetch.ts
> +    ctxFetch = this;
Кажется, что это поле можно убрать и обойтись без него. Чем меньше кода - тем меньше ошибок можно допустить

2022-08-31 16:47 UTC, agadoev commented on src/app.ts
> +                });
1) api.signUp - асинхронный метод и должен вызываться через await
2) Что, если сервер вернет ошибку? Например 500. Надо такие случаи перехватывать и выводить информацию об ошибке пользователю, хотя бы через alert()

2022-08-31 16:47 UTC, agadoev commented on src/app.ts
> +                    formData.get('password') as string
Часто явное приведение типа - знак того, что где-то что-то пошло не так. Скорее всего этот код должен находиться не здесь, а в компоненте, к которому эта форма относится

2022-08-31 16:47 UTC, agadoev commented on src/modules/validate.spec.ts
> +const desc5 = "ValidateForm: Пароль - Должна быть хотя бы одна заглавная буква";
1) Если вдруг бизнес захочет изменить текст об ошибке или например вставить туда ссылку, придется бегать по всем местам в коде, где хранится этот текст. Это не всегда удобно. Текст - это отображение и он должен находиться в компоненте, который рендерит шаблон.
2) Давай названия с цифрами - не очень хороший способ описать, что находится в переменной

2022-08-31 17:00 UTC, Bezumstvo commented
Спасибо, за быстрый ответ, в условиях очередного сорваного дедлайна это бесцено. С доработками согласен в большинстве, но не понял какое основное условие для принятия работы я не выполнил?  опирался на эти пункты - https://practicum.yandex.ru/learn/middle-frontend/courses/3e08c3b3-ed6e-4483-a5c9-6cda18f0c726/sprints/69891/topics/bccb0fbe-eee9-4426-8004-9d2f4d64d732/lessons/e3b1630a-c6e6-4571-89e5-79d465e9f117/

2022-08-31 17:14 UTC, agadoev commented
Все задания выполнены, однако я не могу принять работу, пока у меня есть столько вопросов к коду

2022-08-31 18:41 UTC, agadoev commented
Сейчас писал код по работе и вспомнил принцип один хороший, который может и тебе пригодится
Когда пишешь код, сразу продумывай как его тестировать. Если его сложно протестировать, то скорее всего код спроектирован не очень хорошо и его стоит переписать. На эту тему можно почитать книгу "Экстремальное программирование: разработка через тестирование" Кента Бека

2022-08-31 20:18 UTC, Bezumstvo commented on src/modules/route.spec.ts
> +import { Block } from "./Block";
Согласен это было бы логично, но оставлю как есть т.к. это было в официальном требовнии п.5 "Например, тесты для роутера должны лежать в той же папке, что и файл с кодом роутера. Используйте Mocha и Chai. С Jest вы будете работать в следующем модуле."

2022-08-31 20:40 UTC, Bezumstvo commented on src/app.ts
> +                });
Он и вызывается в самом методе с ( await fetch )  и возвращает промис - сам же выделил код ниже `data.then...` где он и обрабатывает данные - пришли идем на страницу не чата, не пришли - вводи ещё )
При попытке исправить и поставить await выдает ошибку - 'await' expressions are only allowed within async functions and at the top levels of modules.

2022-08-31 20:45 UTC, Bezumstvo commented
> Сейчас писал код по работе и вспомнил принцип один хороший, который может и тебе пригодится Когда пишешь код, сразу продумывай как его тестировать. Если его сложно протестировать, то скорее всего код спроектирован не очень хорошо и его стоит переписать. На эту тему можно почитать книгу "Экстремальное программирование: разработка через тестирование" Кента Бека

Это я уже осознал)) когда пришлось переписывать половину после попыток написать тесты....

2022-09-01 05:57 UTC, Bezumstvo commented on src/modules/Validate.ts
>      }
Поправил, хотя не совсем согласен, здесь идет описание того, что проверяется, а не текст ошибки. Которые потом формируется опираясь на это описание. И  если мы используем этот код в нескольких местах, нам несколько раз приходиться дублировать это описание, что противоречит принципу DRY.  В дальнейшем я вижу развите этого кода как подстановка шаблонной строки i18 и уже в файлах i18 мы меняем описание и что проверяется и самой ошибки... Но в любом случае поправил и убрал. Ксати в предыдущей версии здесь был возврат ошибки, убрал по твоей просьбы, но сейчас могу еще сказать, что тоже на мой взгляд тот подход (подсмотренный где-то в учебных материалах) больше ложится в концепцию TypeScript.

2022-09-01 11:46 UTC, agadoev commented on src/app.ts
> +                });
Да, правильно. await можно использовать только в асинхронных функциях, для этого в addEventListener нужно передать асинхронную функцию с ключевым словом async
Примерно так будет выглядеть
<img width="535" alt="image" src="https://user-images.githubusercontent.com/37894659/187906164-7a613760-5c7a-4f6a-a5d4-47e0bc59c479.png">

Хороший UI/UX обладает отзывчивостью, т.е. на каждое действие пользователь должен получить результат о его действии. Если произошло ошибка или например пользовательский ввод неправильный, то надо как-то уведомить пользователя об этом. Это больше про UI/UX история, но фронтендеру тоже значит полезно

2022-09-01 11:57 UTC, agadoev commented
Привет)
Спасибо за правки, думаю, что код стал чище. Иногда бывает полезно вернуться к коду и посмотреть на него свежим взглядом. Чаще всего решение в лоб не всегда правильное и я, например, часто перепроверяю с утра написанный мною вчера код, потому что я могу найти места, которые стоит переделать. Думаю это полезная привычка, поэтому правки - это нормально)
В любом случая я работу принимаю, удачи в четвертом спринте :)

2022-09-01 11:58 UTC, agadoev approved these changes
Привет)
Спасибо за правки, думаю, что код стал чище. Иногда бывает полезно вернуться к коду и посмотреть на него свежим взглядом. Чаще всего решение в лоб не всегда правильное и я, например, часто перепроверяю с утра написанный мною вчера код, потому что я могу найти места, которые стоит переделать. Думаю это полезная привычка, поэтому правки - это нормально)
В любом случая я работу принимаю, удачи в четвертом спринте :)

2022-09-01 12:18 UTC, Bezumstvo commented on src/app.ts
> +                });
Ты абсолютно прав, в голове даже всплывает что, где-то, когда-то и я про это читал, так что ничего не могу возразить, добавлю в TODO 
p.s. Спасибо за пример!

2022-09-01 12:19 UTC, merged